package org.eclipse.scout.apps.contacts.shared.common;

import org.eclipse.scout.rt.platform.classid.ClassId;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractFormFieldData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;

import javax.annotation.Generated;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@ClassId("d03c9495-530b-4bad-8b05-414ff7edce7a-formdata")
@Generated(value = "org.eclipse.scout.apps.contacts.client.common.AbstractAddressBox", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public abstract class AbstractAddressBoxData extends AbstractFormFieldData {
  private static final long serialVersionUID = 1L;

  public City getCity() {
    return getFieldByClass(City.class);
  }

  public Country getCountry() {
    return getFieldByClass(Country.class);
  }

  public Street getStreet() {
    return getFieldByClass(Street.class);
  }

  @ClassId("9df5daba-9b77-442d-aadd-18d5d1bd59e2-formdata")
  public static class City extends AbstractValueFieldData<String> {
    private static final long serialVersionUID = 1L;
  }

  @ClassId("ed60b3a6-c3aa-4cd3-b82e-341427f744a3-formdata")
  public static class Country extends AbstractValueFieldData<String> {
    private static final long serialVersionUID = 1L;
  }

  @ClassId("8bc1b9dd-6adf-4a48-8ed7-a7c0f0367987-formdata")
  public static class Street extends AbstractValueFieldData<String> {
    private static final long serialVersionUID = 1L;
  }
}
